---
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - db/**/*
    - script/**/*
    - vendor/**/*
    - tmp/**/*
    - app/models/concerns/hyrax/ability.rb
    - lib/active_fedora/solr_service.rb
    - spec/fixtures/**/*
    - app/services/hyrax/workflow/permission_query.rb #temporary, patched from hyrax
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - stage
Metrics/AbcSize:
  Exclude:
    - app/models/xml_import.rb
    - app/lib/tufts/importer.rb
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - app/controllers/catalog_controller.rb
    - spec/**/*
    - app/models/concerns/tufts/**/*
    - lib/tasks/**/*
    - Rakefile
Style/GuardClause:
  Exclude:
    - Rakefile
Metrics/ClassLength:
  Exclude:
    - app/lib/tufts/importer.rb
    - app/controllers/catalog_controller.rb
Layout/LineLength:
  Exclude:
    - app/lib/tufts/importer.rb
    - spec/controllers/tufts/draft_controller_spec.rb
    - spec/support/stub/stub_exif.rb
    - lib/tasks/fix_1143.rake
Metrics/ModuleLength:
  Exclude:
    - app/controllers/concerns/hyrax/works_controller_behavior.rb
Metrics/MethodLength:
  Exclude:
    - app/lib/tufts/import_record.rb
    - app/models/forms/contribution.rb
    - app/models/forms/generic_tisch_deposit.rb
    - lib/tasks/import_test_file.rake
    - app/lib/tufts/importer.rb
    - app/controllers/concerns/hyrax/works_controller_behavior.rb
Performance/StringReplacement:
  Exclude:
    - app/controllers/tufts/works_controller.rb
RSpec/DescribeClass:
  Exclude:
    - spec/lib/tasks/**/*
RSpec/AnyInstance:
  Exclude:
    - spec/controllers/deposit_types_controller_spec.rb
    - spec/lib/deposit_types_controller_spec.rb
RSpec/ExampleLength:
  Exclude:
    - spec/features/**/*
    - spec/controllers/tufts/draft_controller_spec.rb
    - spec/controllers/tufts/publication_status_controller_spec.rb
    - spec/controllers/hyrax/audios_controller_spec.rb
    - spec/lib/import_export/deposit_type_importer_spec.rb
    - spec/lib/import_export/deposit_type_exporter_spec.rb
    - spec/lib/deposit_types_controller_spec.rb
    - spec/lib/tufts/workflow_setup_spec.rb
    - spec/controllers/contribute_controller_spec.rb
    - spec/controllers/deposit_types_controller_spec.rb
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Exclude:
    - spec/lib/tufts/input_sanitizer_spec.rb
    - spec/controllers/contribute_controller_spec.rb
    - spec/controllers/tufts/publication_status_controller_spec.rb
    - spec/controllers/hyrax/audios_controller_spec.rb
    - spec/features/**/*
    - spec/jobs/**/*
    - spec/lib/tufts/contribute_collections_spec.rb
    - spec/lib/tufts/metadata_exporter_spec.rb
    - spec/lib/tufts/workflow_setup_spec.rb
    - spec/services/**/*
    - spec/support/shared_examples/metadata_ordered_fields.rb
RSpec/NestedGroups:
  Max: 4
RSpec/ScatteredSetup:
  Exclude:
    - spec/models/metadata_import_spec.rb
Rails/TimeZone:
  Exclude:
    - config/initializers/git_sha.rb
Naming/FileName:
  Exclude:
    - "**/Capfile"
    - "**/Gemfile"
    - "**/*.rake"
    - "config/deploy/*"
Style/MissingRespondToMissing:
  Exclude:
    - app/models/concerns/hyrax/file_set/characterization.rb
Style/MethodMissingSuper:
  Exclude:
    - app/models/concerns/hyrax/file_set/characterization.rb
    - spec/lib/tufts/handle_registrar_spec.rb
RSpec/InstanceVariable:
  Exclude:
    - spec/models/metadata_import_spec.rb
    - spec/lib/tufts/handle_registrar_spec.rb
    - spec/lib/tufts/handle_registrar_spec.rb
    - spec/lib/tufts/handle_registrar_spec.rb
Security/YAMLLoad:
  Exclude:
    - config/initializers/devise.rb
    - config/initializers/redis_config.rb
Lint/UselessAssignment:
  Exclude:
    - app/lib/tufts/contribute_collections.rb
RSpec/LetSetup:
  Exclude:
    - spec/features/create_collection_spec.rb
    - spec/features/add_work_to_collection_spec.rb
