---
:queues:
  - [ingest, 4]
  - [batch, 2]
  - [handle, 1]
  - [default, 1]
  - [tdr_derivative_queue, 3]
  - [fixity_check, 1]
  - [batch_recreate_video_derivatives, 1]
  - [collection_indexer, 1]

:limits:
  tdr_derivative_queue: 3
  ingest: 5
  batch: 5
  handle: 5
  fixity_check: 1
  default: 5
  batch_recreate_video_derivatives: 2
  collection_indexer: 1

test:
  :concurrency: 1

development:
  :concurrency: 5

stage:
  :concurrency: 3

production:
  :concurrency: 5
